### ISSUE TITLE
Duplication Unsupported : weird IDs and error messages when duplicate a product from another

### ISSUE THREAD

**Issue by mmtomm** [facebookincubator/facebook-for-woocommerce#101]
I setup a product and then 3 others as duplicate from the first one, just changing stuff like SKU, colors etc.
But with the first one I have some problems when saving it:
Facebook extension error: Facebook for WooCommerce
(#803) Some of the aliases you requested do not exist: 1.5849546248847E+15

It also states: 
Facebook for WooCommerce
Created product group 1.5849546248847E+15 on Facebook.
But I was not intended to create a product group.

I deleted the custom field (which is obviously autmatically created) fb_product_group_id = 1.5849546248847E+15 also do a reset facebook metadata and even Delete product(s) on Facebook, but it always comes back with this strange product ID 1.5849546248847E+15

**Comment by sammul** [comment]
Hi

Hello,

Thanks for writing in.

Could you tell us the plugin version you are using? 
If you are not using the latest version(1.6.5), can you update and try again?

Thanks

Xia

**Comment by mmtomm** [comment]
Hello,

I updated to 1.6.5 now, but the problem is still the same!

**Comment by dmitridr** [comment]
Hello,

If you duplicate a product that has been synced to FB there is definitely a problem, as mentioned in #62 you'd have to reset FB metadata after duplicating. I see you already tried that and the problem is with the first product, which is strange. 

One potential workaround is that you could try 'Force Resync' after you are done saving all the products, which could resolve the issue, but could be annoying to do that every time after duplicating because resync takes a while. 

In order for us to reproduce the problem on our test servers, could I ask you to send us a list of detailed steps to reproduce the issue? Once we can reproduce the issue, we can fix it. I tried a simple duplication just now on our test server and erased the metadata but did not encounter your issue.

**Comment by mmtomm** [comment]
Hello,

me again with the same issue but this time it appears without doing a product duplication but with a new product from scratch (type virtual).
It does produce again strange fb-IDs like https://www.facebook.com/1.4457353822194E+15
any idea?
Thank you

**Comment by dmitridr** [comment]
Hello,

Can you send a screenshot of where you are seeing the strange ID?
Detailed steps to reproduce the issue would also be helpful! 
I have tried to create a new virtual product but I cannot reproduce the problem on our side...

So I suspect the problem is potentially due to a conflict with another one of your plugins.

P.S. We've fixed the old duplication issue, the fix will be out in the next version.

**Comment by mmtomm** [comment]
Hello,

it is only arbitrary to reproduce.
It happens while creating new products of any type (from the scratch or from duplicating), but also when I use the 'reset facebook metadata' link.

the screenshot shows the ID which forms this link:
https://facebook.com/1.4457353822194E+15
![screenshot-2017-12-14 produkt bearbeiten guterstoff wordpress](https://user-images.githubusercontent.com/31536991/33991599-73a076a4-e0cf-11e7-8ac3-f9bf3fce61e1.png)

Any idea how I could provide you with more information to get this one catched?
Thank you
Tom

**Comment by dmitridr** [comment]
Hello Tom,

- One thing I recommend trying, is to temporarily deactivate all plugins except Facebook for WooCommerce and WooCommerce. Then seeing if the problem still occurs. If the problem goes away, there is a conflict with one of the plugins.
- You should also consider upgrading to [v1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3), the duplication problem is fixed in that version. You will no longer need to reset meta-data.
- If this doesn't go away, we can move forward on this if you send us temporarily login credentials to ads_extension_woocommerce@fb.com and we can try and take a look directly. We may be able to identify and fix the problem this way. We would need permission to edit our plugin, and a product we can test with.

My guess is the Facebook ID is being converted to a floating point number somewhere, whereas it should be a long. We can probably find that place and use a string instead.

**Comment by it-bel** [comment]
Hello, I have the same issue when I create or update some product.

"Facebook extension error: Facebook for WooCommerce
(#803) Some of the aliases you requested do not exist: 1.4586414275821E+15"

It only occurs on some products.
I've tried to reset the Facebook metadata with no effect. I still have the error.
I have the version 1.7.5 of the facebook for woocommerce extension.

I can give you temporarily login credentials and a product to test.

Regards

**Comment by mmtomm** [comment]
Hi again on this one with plugin version 1.7.11 installed (and all woo, plugins and wp uptodate).
With the newer versions installed it looked like it worked but using 'reset facebook metadata' it appears again.
It comes with the error message "Facebook extension error: Facebook for WooCommerce
(#803) Some of the aliases you requested do not exist: 1.6579594242972E+15"
I changed something on [this product](https://business.facebook.com/commerce/products/1657959427630544/) after this the facebook id was linking [to this url](https://www.facebook.com/1.6579594242972E+15).

Regards
Tom

**Comment by dmitridr** [comment]
Thanks all for your patience. This issue has been open for a long time now and we still don't have a great idea for what's going on. It seems related to `reset facebook metadata` judging by the last comment.

@it-bel if you're still willing to share credentials with us, please email them to ads_extension_woocommerce@fb.com it would be helpful if we had permission to edit the plugin live to test potential fixes.

v1.8.0 changed the way product sync works, so it may have fixed the problem as well.

**Comment by it-bel** [comment]
Hello,

I've just send you an email at ads_extension_woocommerce@fb.com with the credentials.

Regards

**Comment by chris-let** [comment]
Just adding that I'm having the same issue with https://auxibag.com/ and https://www.facebook.com/auxibag/ - I had to reset the fb store which means that it's been offline for the last couple of days while it's being re-approved. Happy to give more details of my specific issue - but it seems to be similar to this: https://github.com/facebookincubator/facebook-for-woocommerce/issues/122 - but resetting the metadata doesn't help - each duplicated product was showing up with the same product id on fb.
Best
Chris

**Comment by jieminz22** [comment]
Hi @chris-let,

Do you have your issue solved? Also which version are you using?

**Comment by chris-let** [comment]
Thanks for getting in touch. I'm reluctant to try again as I'm live & don't have a proper testing environment set up for this. This issue was on the latest release, though.

**Comment by mengyingdu** [comment]
Hi @chris-let ,

I checked on your site, your plugin version is 1.6.6 which is pretty old.  Currently we are on [v1.8.5](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.5), and use feed approach to sync all products after set-up which will only takes several minutes to finish. We also support auto-upgrade detection for Wordpress built-in plugin checking.

Can you upgrade your plugin and re-setup from scratch?
1. woocommerce settings --> integration --> facebook-for-woocommce -> reconfig your settings --> advance options --> delete your settings
2. in your left panel find 'plugins' tab --> deactivate and delete 'facebook for woocommerce'
3. 'add new' plugin and 'upload' the latest version (you can download from the hyper link  v1.8.5)
4. activate this plugin
5. go back to the plugin admin panel as described in step 1
6. 'get started'

Since we have many fixes and features  for new versions, I would strongly suggest you try. Same suggestion to @mmtomm 


Thanks.

**Comment by chris-let** [comment]
Hi @mengyingdu

Thanks for that - I will upgrade asap. I'm surpirsed that it's an old
version - this was the version that was available via the plugin page in
the WordPress admin interface. I wonder if the updates are being pushed out
correctly?

Thanks again

Chris


Chris

Chris Baldwin
Founder/Head consultant
eLearning Path
www.elearning-path.com

**Comment by dmitridr** [comment]
We finally figured out the cause and @mengyingdu  fixed this recently in [this commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/1e0397e0744b6cc10194c1c2855976c414fb2943). The fix should be out in the next version, v1.9.0.

**Comment by mengyingdu** [comment]
Hi @mmtomm , @it-bel , @chris-let ,

This was fixed in [v1.9.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.0).
