### ISSUE TITLE
Custom Audience Errors using Facebook Pixel

### ISSUE THREAD

**Issue by aluxh** [facebookincubator/facebook-for-woocommerce#242]
Hello! Although I can see lots of events happening in the pixel page, 

1. When I create custom audience, my audience size is always -1.
2. When I look at my events, it is showing some errors about advanced matching. 

But, I don't know how should I fix this while using the WooCommerce plugin.  Please advise.

![image](https://user-images.githubusercontent.com/1736667/35546609-e5b54e36-05af-11e8-8b82-f359bdacddda.png)
![image](https://user-images.githubusercontent.com/1736667/35546704-55a7cfac-05b0-11e8-81f5-c8fbd55661be.png)

**Comment by mengyingdu** [comment]
Hi @aluxh,

If you see error in custom audience creation, we can divide it into 2 possible reasons:
1. plugin 
2. custom audience creation flow

Now I want to repo your issue but i need more information from you:

Which version of plugin are you using?
What's your site url and fb page url? 

Thanks.

**Comment by aluxh** [comment]
Hi @mengyingdu,

1. I'm using Version 1.6.6.
2. site url: https://myredlotus.com
fb page url: https://www.facebook.com/myredlotus

Thanks!

**Comment by mengyingdu** [comment]
Hi @aluxh,

I checked your site, the advance matching doesn't work. If it works correctly, you should be able to see sth like this: (this is my demo store)
![screen shot 2018-02-01 at 12 40 34 pm](https://user-images.githubusercontent.com/24535640/35702289-97ccfb2a-074d-11e8-916a-331b22c18ce7.png)

I would recommend you upgrade your plugin to the latest one [v1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11)
And you can easily check whether the advanced matching works by 'Facebook Pixel Helper' (It's in chrome extension store and it is free.)

Let me know if it works.

Thanks.

**Comment by aluxh** [comment]
I have upgraded the plugin to the latest one. Will monitor for a day.

**Comment by aluxh** [comment]
I have tried, and it still doesn't work. The audience size is still -1, and the dashboard still display issues with advanced matching. I wonder anyone faced this issue before?

**Comment by aluxh** [comment]
Hi @mengyingdu, it still doesn't work. Any advice?

**Comment by mengyingdu** [comment]
Hi @jerome2612,

Did you have this problems with v1.7.7 or before? Just want to confirm: you suspect this issue exists only for unregistered shopper, is that correct?

Can you check your commit 'Fix purchase event not firing for Stripe'? Does it break unregister users? @dmitridr

**Comment by jerome2612** [comment]
I can not swear with wich version the problem hapens sorry for that just as I know I have the problem now with v1.7.7 I think I did my last  audience custom with at minimal 3 version older 
The problem is when i want make a custom audience for exemple with people who consulted one specific page IS NOT WORK i have nothing in people audience but audience ready and for my old audience (-1)
that is very weird

**Comment by jerome2612** [comment]
do you think a plug in like YOAST can interfere this result about custom audience??

**Comment by mengyingdu** [comment]
Hi @aluxh,

Could you please tell us detailed steps when you tried to custom audience but saw the weird results? 
For examples, did you see similar interface like this? What's your selected options?
<img width="656" alt="screen shot 2018-02-06 at 4 32 10 pm" src="https://user-images.githubusercontent.com/24535640/35871117-5d05a2a0-0b5b-11e8-8c5a-2e0251f38274.png">

Thanks.

**Comment by jerome2612** [comment]
i said weird result mean "no one" in my custom audience :-) just that 
the step is create new audience --- chose which url visited --- 30 days --- give a name -- and submit 
nothing more 
the thing very bizare it's work only intead of url I chose my fb page but that not realy interest me
do you thing a plug in can interfere with the result of my custom audience

**Comment by jieminz22** [comment]
Hi @jerome2612, 

Are you seeing the same custom audience screen as in @mengyingdu's screenshot above? I don't see the place to enter URL but you need to select a pixel. Which pixel did you select that didn't work for you? If you are seeing some different creation screen, please share us a screenshot. Thanks for you patience!

**Comment by mengyingdu** [comment]
Hi @aluxh ,

As my reply in this thread, I confirmed that advance matching works for registered users (as show in pixel helper) I will flag this issue to our pixel team. Thanks for your report!

Another lucky guess is, the pixel traffic data are delayed data, would you mind wait for more days? 

Also, can you share me the repo steps (screen shot) when you try to create the audience?

Thanks!

**Comment by mengyingdu** [comment]
To clarify, what we expected advance matching:
1. registered user: we log user information together with pixel fire
2. unregistered user: we don't log user information together with pixel fire

**Comment by jerome2612** [comment]
yes i have the same screen to fill the informations @jieminz22 
@mengyingdu i did since more than 6 months more than 20 customs audience and NOW is impossible for the last months i had many fires from my pixel 
![capture d ecran 2018-02-08 a 07 10 18](https://user-images.githubusercontent.com/33776849/35946571-4b8f427a-0c9f-11e8-9a86-4a66f2b1dba8.png)

**Comment by jerome2612** [comment]
@mengyingdu 
i join other screen shot with the box for criteria open 
-->> on YOUR screen shot you have "ANY"
-->> on mine 2 times "ALL"
don't know if it helps
![audience](https://user-images.githubusercontent.com/33776849/35947312-3d02e0c4-0ca2-11e8-94b6-3331f1af271f.jpg)

**Comment by aluxh** [comment]
@mengyingdu 

I used only the default:

![screen shot 2018-02-08 at 2 00 39 pm](https://user-images.githubusercontent.com/1736667/35957853-a9d3faa4-0cd8-11e8-8bbc-86164110faac.png)

Then, after waiting a few more days, the result is still the same. Size is -1.

![screen shot 2018-02-08 at 2 00 54 pm](https://user-images.githubusercontent.com/1736667/35957870-bf007e3e-0cd8-11e8-835a-f89a5543ee99.png)

However, if you look at the dashboard figures, I can see so many events fired.

![screen shot 2018-02-08 at 2 00 48 pm](https://user-images.githubusercontent.com/1736667/35957889-d4dbd99c-0cd8-11e8-99bf-8e9ba608ed3e.png)

Then, you look into the breakdown, you can see how each is performing, but they mentioned advanced matching problems when I touch the "+" symbol.

![screen shot 2018-02-08 at 2 04 00 pm](https://user-images.githubusercontent.com/1736667/35957900-edce0e3e-0cd8-11e8-8646-de6c1a0d155f.png)

**Comment by dmitridr** [comment]
Hey all,

Seems there's 2 separate issues here : (1) Custom Audiences. (2) Advanced matching.

We've passed along your issue with (1) to the team that owns that interface. Unfortunately, we can only help you if there's an explicit problem specific to the plugin, but it seems like this is a problem inside custom audiences. Hopefully that team will resolve the issue, I will update the thread if there is more info from that team. Thanks!

For Advanced Matching (2), this could be a bug we have, but it's benign (no negative impact). Most likely it will be 0% unless the event is Purchase, because advanced matching data (email, name) is usually not available on other events, because the user has not entered this information at that time. If this issue is occurring in Purchase as well, perhaps this is something we can look into and fix.

**Comment by jerome2612** [comment]
@dmitridr your answer about the custom audience means ALL users from FB could NOT use this option...
. This option is the ONE in FB marketing they call it RETARGETING if the users can not use this OPTION for what we pay advertisement ??? 
**Many people continue use this option with SHOPIFFY** no bugs reported I keep hope all this issue will be solve soon as possible because from now if I can nor retarget I will lose all my advertisemt cost.
looking forward

**Comment by aluxh** [comment]
@dmitridr @mengyingdu Would be great to know the results of issue 1. Like @jerome2612 has shared, it is like wasting our advertising money if we cannot capture the audience data for better targeting purposes. Whatever that is happening now in our website, we can't capture anything at all. I don't wish to waste our money if things doesn't work.

**Comment by jerome2612** [comment]
@dmitridr @mengyingdu I looking I search and I would like to be sure with you about something and give you more detail about my configuration 
my theme is https://shopperwp.com and I use child theme 
somewhere in my admin panel in wp I found that shopper/woocommerce/archive-product.php version 2.0.0 est obsolète. La version du noyau est 3.3.0,
shopper/woocommerce/global/quantity-input.php version 3.2.0 est obsolète. La version du noyau est 3.3.0,
shopper/woocommerce/single-product.php
sorry is it french but it mean some template from my theme are not update 
do you think this is a cause from the problem??  because I found the last upsdate on  a update on GITHUB was on 13 december 17 
looking forward I try to keep positive and understand what happen there??

@aluxh your website is under wordpress or shopify ??

**Comment by aluxh** [comment]
@jerome2612 Mine is under Wordpress.

**Comment by jerome2612** [comment]
@dmitridr @mengyingdu Hello there any answers about my last question 
I looking I search and I would like to be sure with you about something and give you more detail about my configuration
my theme is https://shopperwp.com and I use child theme
somewhere in my admin panel in wp I found that shopper/woocommerce/archive-product.php version 2.0.0 est obsolète. La version du noyau est 3.3.0,
shopper/woocommerce/global/quantity-input.php version 3.2.0 est obsolète. La version du noyau est 3.3.0,
shopper/woocommerce/single-product.php
sorry is it french but it mean some template from my theme are not update
do you think this is a cause from the problem?? because I found the last upsdate on a update on GITHUB was on 13 december 17
looking forward I try to keep positive and understand what happen there??

@aluxh your website is under wordpress or shopify ??

**Comment by jerome2612** [comment]
@dmitridr @mengyingdu @aluxh 
after contact FB by tchat they gave a track 
you can read ====>https://developers.facebook.com/ads/blog/post/2018/01/23/reach-estimation-blog/
by chat they explain me the "BUG" appear 23 december but the custom audience still work I'm really not sure and not understand all if you can expose your opinions after read the link will be appreciate :-)
looking forward

**Comment by jerome2612** [comment]
@dmitridr I'm not develep man just an user plus english is not my first langage but on the side from user I'm still try to understand because with @aluxh we are just both of us use retargeting and need to get a minimum of data when we spent money for advertises. So why I'm not find more "complains" about this fact 
Is like I have a car the speed metter no work but the builder says no worries you always under the limit 
**If your application sends an API call with an unsupported reach estimation request after December 22, 2017:**they talk about which API I try to understand if this come from my theme wordpress because it seem people for shopify shop users get the result like normal
We're currently investigating solutions to restore these reach estimates in our interfaces and will provide updates as they're available. More easy  to back at the initial version work and dev side and update when it's work 
thank you

**Comment by dmitridr** [comment]
I get where you're coming from, but from what I understand of the article the API they mean is the `Facebook API` and the interface they mean is the interface you go to when you see the `-1` in Custom Audience, which is separate for Wordpress. I will follow up with the Custom Audience team internally to see if there's any progress.

**Comment by jerome2612** [comment]
ok @dmitridr I had a chat with customer service fb and they told me I can continue use the custom audience .... looking forward your feedback from the custom audience team

**Comment by aluxh** [comment]
@jerome2612 Thanks for sharing all these information. They really help! With the size -1, I'm not even sure about the audience size I'm getting, and it has already past 2 months, and this is still not fixed...

@jerome2612 Could you share how did you get the contact to talk to the Customer Service FB? I was trying to find the contact details, but I couldn't.

@dmitridr Although I understand that the API belongs to Facebook, but the user experience at the end is really bad, because we can't do what we want, or we are receiving misleading messages. So, I'm looking forward to hearing your response from the custom audience team.

It would be great to at least understand when it will be fixed. If it is like 6months time, I think we should have a better workaround from them.

**Comment by jerome2612** [comment]
@dmitridr  sorry again but i dig and dig deep on this subject and WHY people use shoppify have the results from custom audience ??? more than 10 people I asked and different fb group have the results
of the custom audience

**Comment by jerome2612** [comment]
@aluxh this is the link I use for reach fb https://www.facebook.com/facebookadsupport/

**Comment by dmitridr** [comment]
If you suspect the problem is due to Advanced Matching, this feature can be turned off in the plugin via `Reconfigure > Pixel > Advanced Matching (Off) > Save` It is not a feature that is necessary for the pixel to work (but does provide ~10% improvement). I recommend doing this on the off chance it does fix the problem.

I do see that in the document you gave, advanced matching is mentioned... so it could be this is the difference with Shopify that is causing this problem. I am following up with the custom audience team on this.

**Comment by dmitridr** [comment]
Yeah just got confirmation, if your audience has users that were added through advanced matching, it will show `-1`, this was a privacy policy decision that will eventually be fixed in the UI to show something else, i'm trying to get a timeline for this fix.

However, the audience is still populated correctly, if you disable advanced matching, over a period of time (depending on your audience settings) the problem will go away and you should see the normal estimate.

**Comment by jerome2612** [comment]
@dmitridr thank you for clarify this :-) so now if I turn off advanced matching I should wait more than 1000 NEW  events  starting the moment I off the advance matching  to see the results change in the panel audience is it right?
looking forward

**Comment by dmitridr** [comment]
@jerome2612  You may need to wait longer, unfortunately. Depending on how your custom audience is defined. For example if you have the audience defined to website visitors for 30 days, then after turning off Advanced Matching you need to wait 30 days for the bug to fix itself, that's my understanding. The problem as I understand it is there were users in the audience who were Advanced Matched, but we cannot surface this information, not even the number, so we show -1.

I have some questions from the custom audience team that I'd like to relay to you, they want to understand the issue more to fix it. Hope you can answer :
- Are you seeing this -1 in ads manager? If not, where? Can you provide a link to where you are seeing it.
- Did you select any advanced matching options when you created these custom audiences in the interface?

**Comment by jerome2612** [comment]
the -1 appear first appear in asset library now just say "size not available"
but still appear when i'm going  EVENT MANAGER -->PIXEL --> SETTING
https://www.facebook.com/events_manager/pixel/SETTINGS?business_id=343452469416410&pixel_id=1969845839897199&selected_data_sources=PIXEL&selected_screen_section=DATA_SOURCES
![capture d ecran 2018-02-16 a 10 52 14](https://user-images.githubusercontent.com/33776849/36291698-89d6b02c-1307-11e8-8b23-c2d6c53ba4cd.png)
the option advance matching was tick on admin panel for the plug in NOW I already reinstal all the plug in and the box is NOT tick 
![capture d ecran 2018-02-16 a 10 55 35](https://user-images.githubusercontent.com/33776849/36291774-0c4fdc04-1308-11e8-9b50-95a713e6e84a.png)

No worries ask me as you want I want solve this thing and happy to help

**Comment by dmitridr** [comment]
Thanks @jerome2612 ! I think the team understands the problem from the information given now. 
I was told a time estimate for weeks for a fix which actually shows the right size. `Size Not Available` is accurate, I think we may be able to fix that in the short term in `Events Manager` too.

I will update this thread when there is a final fix.

**Comment by jerome2612** [comment]
@dmitridr just a liitle thing if that can help you have 2 ways for making custom audience 
1) from the datas people visited URL from my web site
2) from people react or visit my fb pages 
for 2 I have the result (number people in the audience)
the problem is focus on 1

**Comment by sammul** [comment]
@jerome2612 @aluxh 
The -1 size issue should have been fixed according to the team owns the product. Let us know if you are still seeing -1. Thanks for the reporting

**Comment by aluxh** [comment]
@sammul Now I'm seeing `Size Not Available`, and I need to wait for 30 days to have the number populated? Could you advise what is the minimum population size to see the number? I remember is at least 100 right?

**Comment by jerome2612** [comment]
@dmitridr @sammul same for me -1 became Size Not Available NOT REALLY something interesting change -1 by not available not see the point

**Comment by dmitridr** [comment]
Hey All,

The audience team is working on a way to communicate this information better, stay tuned. 
Though this isn't only related to our plugin, I will keep this issue open until there is an update.

My understanding is that `Size Not Available` will show as long as there are users in your audience who were matched using advanced matching. We are coming up on the 30 day mark, so in about a week you should be able to see if it worked or not. Again, you may have to re-create the audience after the 30 day mark if my understanding is correct. 

Want to set clear expectations here : It's possible that my understanding is not complete and there could be something else that needs to be done also aside from waiting. If so, I'll set aside some time to dig into that after the 30 day mark, and hopefully we can solve it!

Also, if you really don't like `Size Not Available` and want it to go away immediately, another way I can think of is to switch to a brand new pixel and never use advanced matching for this pixel, it should not have this problem.

Thanks for your patience and all your help so far!

**Comment by jerome2612** [comment]
@dmitridr ok waiting the next post

**Comment by dmitridr** [comment]
@jerome2612 Here's the communication from that team:

> As noted in our advertising principles, we're constantly looking to improve the quality and security of our advertising platforms. After identifying a technical issue with reach estimation for Custom Audiences that could potentially allow misuse of the functionality, we're temporarily removing the ability to see audience sizes or potential reach estimates for newly created or edited Custom Audiences in Ads Manager and Power Editor, followed by the Ads API.
> Mainly, we are removing reach estimates for:
> * Custom Audiences from a customer file
> * Offline conversions Custom Audiences (and Offline Conversion API)
> * Website and mobile app Custom Audiences if using advanced matching
> * Offline event data in Facebook Analytics
> Website or mobile app Custom Audiences that do not include customer data and engagement Custom Audiences will not be affected by this update for the most part.
> Please note that you will still be able to create Custom Audiences, as well as ads using any type of Custom Audiences, on our platform. Ads delivery and reporting will remain unaffected by this change.  Additionally, access to all other data in Facebook Analytics will remain unaffected by this change.
> We understand this solution may affect your campaign planning. To minimize disruption, we are currently investigating solutions to restore these reach estimates in our interfaces.
> We appreciate your help in keeping our platform safe.

**Comment by aluxh** [comment]
After waiting for more than 30 days, the pixel is still not working. I have 3.1K pageviews, and my audience is less than 20 after 30 days?

Does it look correct to you?

![image](https://user-images.githubusercontent.com/1736667/38500201-4e45f974-3c3c-11e8-9e2e-e994c77f8152.png)

![audience](https://user-images.githubusercontent.com/1736667/38500155-2a02027e-3c3c-11e8-930f-8b0d99d2b656.png)

**Comment by dmitridr** [comment]
Closing this out because there has been no reply for a while (so I assume all is good). If you continue to have concerns with the plugin specifically please file a new issue on us. If it's a bug in the interface (ads manager, ads creation, etc) it's more effective to file a bug there or report it to FB through other support channels.
