### ISSUE TITLE
Updating Products Returns "(#200) Permissions error" After Updating to 1.7.10

### ISSUE THREAD

**Issue by evenmed** [facebookincubator/facebook-for-woocommerce#246]
Hello,

I just updated from 1.7.5 to 1.7.10 in order to fix the product variations with no descriptions error. That was fixed correctly, but now every time I update a product I get the following message:
<img width="1253" alt="captura de pantalla 2018-01-31 a la s 16 42 18" src="https://user-images.githubusercontent.com/26916296/35651554-c1d48ff8-06a5-11e8-851a-1586122ad249.png">

The product still gets updated fine, both on my site and on my Facebook page. But obviously that error message shouldn't be showing up.

I already tried clearing my cache and cookies and the message still shows.

Any idea why this is happening?

Hope you can help, thanks.

**Comment by Ampmedia-DEV** [comment]
We are having the same issue since the update of WooCommerce yesterday and the Facebook Plugin.  Products are not syncing to Facebook.

**Comment by dmitridr** [comment]
Hello, thanks for flagging this. This was potentially caused by the WooCommerce update it seems?

**Comment by evenmed** [comment]
I didn't update WooCommerce, just the Facebook for WooCommerce plugin.

I think what @Ampmedia-DEV is describing is a different issue from mine though, products are still syncing to Facebook correctly in my case.

In fact, everything is working perfectly fine for me, just that the "(#200) Permissions error" message shows up every time I update a product.

For the record, I'm running WooCommerce 3.2.6

**Comment by Ampmedia-DEV** [comment]
Really not sure about what is causing this.  We have reinstalled WooCommerce this morning and also the Facebook plugin, but we are still experiencing this issue.

**Comment by dmitridr** [comment]
@evenmed Thanks for clarifying. Does downgrading to 1.7.5 fix the problem? We're debugging it now.

**Comment by evenmed** [comment]
Yes, downgrading to 1.7.5 fixes the issue.

**Comment by Ampmedia-DEV** [comment]
Hi, where can I get hold of version 1.7.5?

**Comment by evenmed** [comment]
@Ampmedia-DEV here: https://github.com/facebookincubator/facebook-for-woocommerce/tree/v1.7.5

You can download whatever version of the repository you want in Branch > Tags
<img width="1047" alt="captura de pantalla 2018-01-31 a la s 18 48 18" src="https://user-images.githubusercontent.com/26916296/35655407-57d26db6-06b7-11e8-832d-7c1c95c66297.png">

**Comment by Ampmedia-DEV** [comment]
My bad, thanks

**Comment by evenmed** [comment]
@dmitridr I tried it with different versions and the issue is present since 1.7.9, doesn't happen on 1.7.8 and below.

**Comment by Ampmedia-DEV** [comment]
Great thanks for the tip, will try 1.7.8

**Comment by dmitridr** [comment]
This will greatly help us debug, thanks!
Also recommend using our releases section to downgrade : 
https://github.com/facebookincubator/facebook-for-woocommerce/releases

If you just get the source files from the branch directly, you'll also include the other plugin we have in this repo, `Facebook Pixel for Wordpress`.

**Comment by dmitridr** [comment]
We have a repro, working on isolating and fixing the code responsible, fix will be out in a few hours.

**Comment by Ampmedia-DEV** [comment]
Just an update, version 1.7.8 has fixed all of our issues and facebook Shop is now working again.

We were also have an issue with our Product Variants.  We have high value items that have product variants with pricing ranging from $3,800 to $6,050.  We had set the default variant to the lowest value variant, but Facebook shop kept picking up the highest value variant.  By switching back to 1.7.8 this has also been resolved.

Hopefully the reworked latest version also addresses the variant issue.

Thanks guys.

**Comment by dmitridr** [comment]
Thanks for the report, we'll test to see if there is a regression in the default variant as well as you say. Will delay the fix until sometime tomorrow.

**Comment by mengyingdu** [comment]
Hi @evenmed ,

Thanks for your update and report. This was fixed in [v1.7.11](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11)

**Comment by evenmed** [comment]
Hey @mengyingdu, thanks for fixing this but it looks like you just reuploaded 1.7.10 instead of 1.7.11... 

I downloaded the zip straight from https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.11 and installed it but the error is still there and the plugin says it's version 1.7.10:
<img width="1255" alt="captura de pantalla 2018-02-01 a la s 11 00 28" src="https://user-images.githubusercontent.com/26916296/35691900-62776298-073f-11e8-9e04-1075cbf8e6fe.png">

**Comment by evenmed** [comment]
I downloaded v1.7.11 straight from the master branch and the error was fixed. Hooray!

It's just the 1.7.11 **release** that wrongly contains 1.7.10 instead of 1.7.11

Thanks for fixing this so quickly.
