### ISSUE TITLE
Products not been Synced, count goes to negative

### ISSUE THREAD

**Issue by BlankSuporte5** [facebookincubator/facebook-for-woocommerce#396]
This is the third time i'm trying to sync the products, and the number of products left goes down to 0, and keeps going to -1, -2, -3...

![image](https://user-images.githubusercontent.com/38261894/38577977-e7bc5110-3cd8-11e8-834d-8323f8a3b8c5.png)

![image](https://user-images.githubusercontent.com/38261894/38578080-3817dc2e-3cd9-11e8-83b7-1c6e475cfe58.png)

It says that I have all my 77 products synced, but after it started going <0, it starts syncing a lot of the same product

![image](https://user-images.githubusercontent.com/38261894/38578113-59db40c6-3cd9-11e8-9b5a-9def9eadb375.png)

And when I try to Force Product Resync, it still goes from <0

Facebook for Woocommerce plugin version: 1.8.4

Facebook shop page: https://www.facebook.com/pg/EclairMoiSP/shop/?ref=page_internal
Woocommerce shop page: https://eclairmoi.com/loja/
Catalog ID: 158817084797464

**Comment by sammul** [comment]
Thanks for reporting. That is so weird. We are looking into it.

**Comment by dmitridr** [comment]
Hello, 

We've removed product count entirely in recent versions, 1.8.2. and above. It only exists now for backwards compatibility and is really slow.

If it's causing you trouble or if you want to upgrade to the new method, please reset the plugin entirely, the new force resync sync method does not count down negative and is much much faster.

**Comment by BlankSuporte5** [comment]
Where can I find this "Reconfigure"?

**Comment by BlankSuporte5** [comment]
After reconfiguring and deleting again:

![instagram1](https://user-images.githubusercontent.com/38261894/38679546-6df29a20-3e3a-11e8-9f81-1200fb8d9a7a.png)

![instagram2](https://user-images.githubusercontent.com/38261894/38679547-6e39d3c2-3e3a-11e8-8030-4f7ad4fe7caf.png)

**Comment by dmitridr** [comment]
Hey again,

Pretty crazy that the negative numbers appeared again. 
We do a curl to Facebook in order to upload the feed file, if the curl fails, we default back to the old upload method (with the negative numbers) that must be what you are seeing.

Does your server support curl? If it does not, that may be the cause.

**Comment by BlankSuporte5** [comment]
#Update 2#

Openning each product and updating it creates the product in facebook and it works

**Comment by dmitridr** [comment]
Great to hear that you've resolved the issue. Doing a quick-edit or bulk-edit should also work.

Regarding the `same product keeps being uploaded` issue that you mentioned above, this is just the way variants are displayed in that interface, they are uploaded to FB as different products (because they could have different price/etc). But in most cases they have the same image and name, so you may see a bunch of the same products, but that won't be what your users see in the shop.

Closing this out since it seems the issue is resolved, but if you continue to have issues feel free to open a new issue and reference this one.

**Comment by tagor3** [comment]
its been 3 years, plugin is still not fixed
![image](https://user-images.githubusercontent.com/37122241/76138191-717ce880-606b-11ea-8b80-ed085832b358.png)
