### ISSUE TITLE
deleted products still uploaded to facebook (also as invisible / private or concept products) 

### ISSUE THREAD

**Issue by frisonl** [facebookincubator/facebook-for-woocommerce#75]
**the following problem occures:**

deleted products (also products that are set as invisible / private or concept) are still uploaded to facebook and visible in the shop section on facebook. Products in trash show up on facebook. Also after resync and reset. Only if a permanently delete them, they also disappear on facebook. 

I have the latest wordpress and woocommerce in Dutch as primary language. 

Please let me know what information you need to see what could be the source of this. 

Thank you

**Comment by dmitridr** [comment]
Hello,

Could you please confirm you are using version 1.6.1 or above? We fixed an issue with hidden products in this version, but we are not actively checking if the product is in the 'trash' or not.

**Comment by frisonl** [comment]
Hi Dmitridr, ah. I had 1.4.1, but it wasn't showing an update so I assumed I had the newest version. Forgot that I didn't install it via the wordpress plugin 'market'. Anyway. I seems the problem is still there:

Just deleting, no update on facebook, also not after force sync

Also changing the status to concept or private doesn't change the status on facebook.

I know saw (i think a new option after the update?) the option to 'HIDE' products on facebook. That us useful for now anyway.

I hope I can help to find out what is the issue, because I guess it should automatically remove unpublished or private products?

Thanks for the help and the plugin.

**Comment by dmitridr** [comment]
Glad the update helped you out!

If you could send us a screenshot of the configuration for 'unbublished' or 'private' products this would help use figure out the issue further. I also don't see where to change the status of a product to 'concept' or 'private' is this functionality added by another plugin?

I tried testing this on our servers with a 'draft' product which I'm guessing is the same as 'unpublished', but can't reproduce the problem: the product will not sync to FB for me. 

When you create a new draft product under the new version, are you still having this issue that it syncs to FB? If so could you enumerate the steps for that so that I can reproduce the problem?

**Comment by frisonl** [comment]
Thank you for the feedback. Below some tests I did that might help for you to find out what the issue could be.

Screenshot of product in trash that is not showing in facebook (which is good)
![image](https://user-images.githubusercontent.com/18679678/31482099-18409016-af27-11e7-8538-e18aadf06f79.png)

I was talking about these settings (sorry, concept is dutch for draft i realized now)
![image](https://user-images.githubusercontent.com/18679678/31482138-4bd10c3a-af27-11e7-9ef9-43b3d70d4c83.png)

**Below some tests that might help to solve it:**

I have a Dutch/English woocommerce setup. I do all the below steps in the English version, but primary language of the setup is Dutch. (could it be a language issue?) In all tests below I leave the SHOW button for facebook on, or the HIDE off, for that matter.

**new test**
step 1:
with these settings it is showing on facebook:
![image](https://user-images.githubusercontent.com/18679678/31482240-ce36a3ba-af27-11e7-9fb8-32e03a5af539.png)

step2: i set it back to private, but published on: Now still showing on facebook (also after forece resync all)
![image](https://user-images.githubusercontent.com/18679678/31482305-0e01ec48-af28-11e7-8eb6-6c05e7ac5db9.png)

step 3: is also turn on hidden: Now still showing on facebook (also after forece resync all)
![image](https://user-images.githubusercontent.com/18679678/31482410-7e5112da-af28-11e7-830f-f0f583fa40a4.png)

step4: now with stettings private, hidden, in trash: Now still showing on facebook (also after forece resync all)
![image](https://user-images.githubusercontent.com/18679678/31482602-385bce5e-af29-11e7-91b4-a9cc4a500316.png)

step 5: moved back from trash and turn off private, but set is a draft: Now still showing on facebook (also after forece resync all)
![image](https://user-images.githubusercontent.com/18679678/31482651-6ed0a18a-af29-11e7-9068-b281f7be44a7.png)

step 6: with setting of step 5 in trash: Now still showing on facebook (also after forece resync all)

step 7: now I do click the HIDE buton for facebook, and it indeed does go to unplished in my facebook business manager.  even no force resync needed

step 8: turned HIDE back to SHOW and then permanently deleted from trash immediatly gone, even no force resync needed

**Comment by dmitridr** [comment]
Great, thank you for the detailed steps! We will verify and fix that.

**Comment by frisonl** [comment]
You're welcome. Thanks for your work on it.

**Comment by perrochon** [comment]
Any update? I Saw similar/same thing, and came here to file. "moved to trash" in two items, but they didn't go away on Facebook. Then "delete permanently" and that did the job. But I don't want to delete permanenly. Version 1.6.6

**Comment by mengyingdu** [comment]
Hi,

I'm currently working on this issue and will update a fix in next new version. Since we are in code freeze timing, next release will be after 28th Nov ASAP. Thanks for your patience.

**Comment by mengyingdu** [comment]
Hi,

Version [1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.0) is ready, can you try to upgrade?

Thanks.

**Comment by frisonl** [comment]
Alright I will a.s.a.p. Thank you for the update!
